- name: Initialize development environment
  hosts: localhost

  tasks:
    - name: Install packages with apt
      become: true
      ansible.builtin.apt:
        name:
          - build-essential
          - fzf
          - git
          - ninja-build
          - tmux
          - software-properties-common
          - python3-pip
          - python3-venv
        state: present

    - name: Pull git extensions
      ansible.builtin.git:
        repo: git@github.com:TheMikeste1/git-galaxy.git
        dest: ./git_commands

- name: Setup CMake
  ansible.builtin.import_playbook: playbooks/cmake.yaml
  tags:
    - cmake

- name: Setup Fish
  ansible.builtin.import_playbook: playbooks/fish.yaml
  tags:
    - fish

- name: Setup NeoVim
  ansible.builtin.import_playbook: playbooks/neovim.yaml
  tags:
    - neovim

- name: Setup Rust
  ansible.builtin.import_playbook: playbooks/rust.yaml
  tags:
    - rust

- name: Setup WSL Utilities
  ansible.builtin.import_playbook: playbooks/wslview.yaml
  tags:
    - wsl

- name: Setup Zsh
  ansible.builtin.import_playbook: playbooks/zsh.yaml
  tags:
    - zsh

- name: Link
  hosts: localhost

  tasks:
    # TODO: Replace this script entirely
    - name: Run Python initialization script
      ansible.builtin.script: ./init.py
      environment:
        DOTFILES: "{{ playbook_dir }}"
