version: 2
final_space: true
console_title_template: '{{ .Shell }} in {{ .Folder }}'
blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        style: plain
        background: transparent
        foreground: blue
        template: '{{ .Path }}'
        properties:
          style: full
      - type: git
        style: plain
        foreground: p:grey
        background: transparent
        templates:
          - ' {{.HEAD}}'
          - '{{if or (.Working.Changed) (.Staging.Changed)}}*{{end}}'
          - ' <cyan>{{.BranchStatus}}</>'
          - ' {{ if gt .StashCount 0 }} {{ .StashCount }}{{ end }}'
        properties:
          branch_icon: ''
          commit_icon: '@'
          fetch_status: true
  - type: prompt
    alignment: right
    segments:
      - type: sysinfo
        templates:
          - '{{if gt .PhysicalPercentUsed 80}}  {{ round .PhysicalPercentUsed .Precision }}%{{end}}'
        properties:
          precision: 2
      - type: cmake
        style: plain
        cache_version: true
        template: '  {{ .Full  }}'
      - type: node
      - type: go
      - type: lua
        style: plain
        template: '  {{ .Full }}'
      - type: python
      - type: rust
      - type: dotnet
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        foreground_templates:
          - '{{if gt .Code 0}}red{{end}}'
          - '{{if eq .Code 0}}green{{end}}'
        background: transparent
        templates: ['{{if gt .Code 0}}{{end}}', '{{if eq .Code 0}}❯{{end}}']
        templates_logic: first_match
  - type: rprompt
    overflow: hidden
    segments:
      - type: executiontime
        style: plain
        foreground: yellow
        background: transparent
        template: '{{ .FormattedMs }}'
        properties:
          threshold: 5000
      - type: status
        style: plain
        foreground: red
        background: transparent
        properties:
          status_template: '{{if ne .Code 0}}{{reason .Code}} {{ .Code -}}{{end}}'
transient_prompt:
  foreground_templates:
    - '{{if gt .Code 0}}red{{end}}'
    - '{{if eq .Code 0}}green{{end}}'
  background: transparent
  template: '{{if gt .Code 0}}{{else}}❯{{end}} '
secondary_prompt:
  foreground: green
  background: transparent
  template: '> '
