# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[c]
format = 'via [$name $version]($style) '
detect_extensions = ['c', 'cpp', 'cxx', 'h', 'hpp', 'hxx']
detect_folders = ["include"]

[character]
error_symbol = "[✖](bold red) "

[git_status]
windows_starship = "git"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[line_break]
disabled = false

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[python]
python_binary = 'python3'
