---
- name: Check for CMake
  hosts: localhost
  tasks:
    - command: "which cmake"
      check_mode: false
      changed_when: false
      failed_when: cmake_installed.rc > 0
      register: cmake_installed
      ignore_errors: true

- name: Install CMake from apt
  ansible.builtin.import_playbook: apt/cmake.yaml
  when: false

- name: Build CMake
  ansible.builtin.import_playbook: build/cmake.yaml
  when: cmake_installed.failed
