---
- name: Check for NeoVim
  hosts: localhost
  tasks:
    - name: Check whether NeoVim is installed and on system path
      command: "which nvim"
      check_mode: false
      changed_when: false
      failed_when: nvim_installed.rc > 0
      register: nvim_installed
      ignore_errors: true

- name: Build NeoVim
  ansible.builtin.import_playbook: build/neovim.yaml
  when: nvim_installed.failed

- name: Initialize NeoVim
  hosts: localhost
  tasks:
    - name: Pull NeoVim config
      ansible.builtin.git:
        repo: git@github.com:TheMikeste1/my-neovim.git
        dest: ~/.config/nvim
        update: false
