---
- name: Check for NeoVim
  hosts: localhost
  tasks:
    - name: Check whether NeoVim is installed and on system path
      command: "which nvim"
      register: nvim_installed
      ignore_errors: true

- name: Build NeoVim
  ansible.builtin.import_playbook: build/neovim.yaml
  when: not nvim_installed

- name: Initialize NeoVim
  hosts: localhost
  tasks:
    - name: Pull NeoVim config
      ansible.builtin.git:
        repo: git@github.com:TheMikeste1/my-neovim.git
        dest: ~/.config/nvim
        update: false
