- name: Initialize Rust and Packages
  hosts: localhost

  tasks:
    - name: Check if Rust is installed
      shell: command -v rustup
      register: rust_installed
      ignore_errors: true

    - name: Download Rust installer
      when: rust_installed is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: true

    - name: Install Rust
      when: rust_installed is failed
      shell: /tmp/sh.rustup.rs -y

    - name: Install sccache to speed up Rust compilation
      community.general.cargo:
        name:
          - sccache
        state: present

    - name: Install Rust packages
      community.general.cargo:
        name:
          - bat
          - git-delta
          - exa
          - fd-find
          - mise
          - ripgrep
          - starship
        state: present
      environment:
        RUSTC_WRAPPER: sccache
