---
- name: Initialize ZSH
  hosts: localhost

  tasks:
    - name: Install Zsh
      become: true
      ansible.builtin.apt:
        name:
          - zsh
        state: present
    - name: Set Zsh as default shell
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh

    - name: Check whether oh-my-posh is installed and on system path
      command: "which oh-my-posh"
      register: omp_installed
      ignore_errors: true
    - name: Install oh-my-posh
      command: curl -s https://ohmyposh.dev/install.sh | bash -s
      when: not omp_installed

